services:
  backend:
    container_name: react-node-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001      
      - MONGO_URI=mongodb://mongo:27017/wanted-db
      - FRONTEND_DOMAIN=http://frontend:8092
      - FBI_WANTED_API_URL=https://api.fbi.gov/wanted/v1/list
      - FBI_WANTED_API_UID_URL=https://api.fbi.gov/@wanted-person
      - FRONTEND_DOMAIN_TWO=http://localhost:3000

    volumes:
      - ./server:/usr/src/app
      #- /usr/src/app/node_modules
    networks:
      - wanted-network

  frontend:
    container_name: react-node-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      #- "8092:80" if nginx proxy is used
      - "8092:3000"  # Match Next.js default port
    environment:
      - NEXTAUTH_SECRET=b31d032cfdcf47a399990a71e43c5d2a
      - REACT_APP_API_BASE_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - wanted-network

networks:
  wanted-network:
    driver: bridge
